-- Phase 2: Full UniversityMaster import
-- Source: univ_uni_11_01_2566.xlsx, UNIV_NAME column (454 records)
-- Main institution English names use official/common English names.
-- Campus/center English labels are standardized from institution, site type, province, and source code.

INSERT INTO "UniversityMaster"
  ("id", "nameTh", "nameEn", "isActive", "createdAt", "updatedAt")
VALUES
('mhesi-00100', 'จุฬาลงกรณ์มหาวิทยาลัย', 'Chulalongkorn University', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-00200', 'มหาวิทยาลัยเกษตรศาสตร์', 'Kasetsart University', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-00201', 'มหาวิทยาลัยเกษตรศาสตร์ วิทยาเขตกำแพงแสน', 'Kasetsart University — Campus, Nakhon Pathom (00201)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-00202', 'มหาวิทยาลัยเกษตรศาสตร์ วิทยาเขตศรีราชา', 'Kasetsart University — Campus, Chon Buri (00202)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-00203', 'มหาวิทยาลัยเกษตรศาสตร์ วิทยาเขตเฉลิมพระเกียรติ จังหวัดสกลนคร', 'Kasetsart University — Campus, Sakon Nakhon (00203)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-00204', 'มหาวิทยาลัยเกษตรศาสตร์ วิทยาเขตสุพรรณบุรี', 'Kasetsart University — Campus, Suphan Buri (00204)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-00210', 'มหาวิทยาลัยเกษตรศาสตร์ บางเขน', 'Kasetsart University — Main Campus, Bangkok (00210)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-00300', 'มหาวิทยาลัยขอนแก่น', 'Khon Kaen University', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-00301', 'มหาวิทยาลัยขอนแก่น วิทยาเขตหนองคาย', 'Khon Kaen University — Campus, Nong Khai (00301)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-00400', 'มหาวิทยาลัยเชียงใหม่', 'Chiang Mai University', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-00500', 'มหาวิทยาลัยธรรมศาสตร์', 'Thammasat University', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-00501', 'มหาวิทยาลัยธรรมศาสตร์ ศูนย์ลำปาง', 'Thammasat University — Education Center, Lampang (00501)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-00502', 'มหาวิทยาลัยธรรมศาสตร์ ศูนยรังสิต', 'Thammasat University — Campus, Pathum Thani (00502)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-00503', 'มหาวิทยาลัยธรรมศาสตร์ ศูนยถาวร-อุษา ประภา(ศูนย์พัทยา)', 'Thammasat University — Education Center, Chon Buri (00503)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-00600', 'มหาวิทยาลัยมหิดล', 'Mahidol University', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-00601', 'มหาวิทยาลัยมหิดล วิทยาเขตกาญจนบุรี', 'Mahidol University — Campus, Kanchanaburi (00601)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-00602', 'มหาวิทยาลัยมหิดล วิทยาเขตนครสวรรค์ (โครงการจัดตั้งวิทยาเขต)', 'Mahidol University — Campus, Nakhon Sawan (00602)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-00603', 'มหาวิทยาลัยมหิดล วิทยาเขตอำนาจเจริญ', 'Mahidol University — Campus, Amnat Charoen (00603)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-00700', 'มหาวิทยาลัยรามคำแหง', 'Ramkhamhaeng University', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-00701', 'มหาวิทยาลัยรามคำแหง วิทยาเขตบางนา', 'Ramkhamhaeng University — Campus, Bangkok (00701)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-00702', 'มหาวิทยาลัยรามคำแหง สาขาวิทยบริการเฉลิมพระเกียรติจังหวัดกาญจนบุรี', 'Ramkhamhaeng University — Academic Services Branch, Kanchanaburi (00702)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-00703', 'มหาวิทยาลัยรามคำแหง สาขาวิทยบริการเฉลิมพระเกียรติจังหวัดขอนแก่น', 'Ramkhamhaeng University — Academic Services Branch, Khon Kaen (00703)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-00704', 'มหาวิทยาลัยรามคำแหง สาขาวิทยบริการเฉลิมพระเกียรติจังหวัดชัยภูมิ', 'Ramkhamhaeng University — Academic Services Branch, Chaiyaphum (00704)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-00705', 'มหาวิทยาลัยรามคำแหง สาขาวิทยบริการเฉลิมพระเกียรติจังหวัดเชียงราย', 'Ramkhamhaeng University — Academic Services Branch, Chiang Rai (00705)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-00706', 'มหาวิทยาลัยรามคำแหง สาขาวิทยบริการเฉลิมพระเกียรติจังหวัดเชียงใหม่', 'Ramkhamhaeng University — Academic Services Branch, Chiang Mai (00706)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-00707', 'มหาวิทยาลัยรามคำแหง สาขาวิทยบริการเฉลิมพระเกียรติจังหวัดตรัง', 'Ramkhamhaeng University — Academic Services Branch, Trang (00707)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-00708', 'มหาวิทยาลัยรามคำแหง สาขาวิทยบริการเฉลิมพระเกียรติจังหวัดนครพนม', 'Ramkhamhaeng University — Academic Services Branch, Nakhon Phanom (00708)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-00709', 'มหาวิทยาลัยรามคำแหง สาขาวิทยบริการเฉลิมพระเกียรติจังหวัดนครราชสีมา', 'Ramkhamhaeng University — Academic Services Branch, Nakhon Ratchasima (00709)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-00710', 'มหาวิทยาลัยรามคำแหง สาขาวิทยบริการเฉลิมพระเกียรติจังหวัดนครศรีธรรมราช', 'Ramkhamhaeng University — Academic Services Branch, Nakhon Si Thammarat (00710)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-00711', 'มหาวิทยาลัยรามคำแหง สาขาวิทยบริการเฉลิมพระเกียรติจังหวัดบุรีรัมย์', 'Ramkhamhaeng University — Academic Services Branch, Buriram (00711)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-00712', 'มหาวิทยาลัยรามคำแหง สาขาวิทยบริการเฉลิมพระเกียรติจังหวัดปราจีนบุรี', 'Ramkhamhaeng University — Academic Services Branch, Prachin Buri (00712)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-00713', 'มหาวิทยาลัยรามคำแหง สาขาวิทยบริการเฉลิมพระเกียรติจังหวัดพังงา', 'Ramkhamhaeng University — Academic Services Branch, Phang Nga (00713)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-00714', 'มหาวิทยาลัยรามคำแหง สาขาวิทยบริการเฉลิมพระเกียรติจังหวัดเพชรบูรณ์', 'Ramkhamhaeng University — Academic Services Branch, Phetchabun (00714)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-00715', 'มหาวิทยาลัยรามคำแหง สาขาวิทยบริการเฉลิมพระเกียรติจังหวัดแพร่', 'Ramkhamhaeng University — Academic Services Branch, Phrae (00715)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-00716', 'มหาวิทยาลัยรามคำแหง สาขาวิทยบริการเฉลิมพระเกียรติจังหวัดลพบุรี', 'Ramkhamhaeng University — Academic Services Branch, Lop Buri (00716)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-00717', 'มหาวิทยาลัยรามคำแหง สาขาวิทยบริการเฉลิมพระเกียรติจังหวัดศรีสะเกษ', 'Ramkhamhaeng University — Academic Services Branch, Sisaket (00717)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-00718', 'มหาวิทยาลัยรามคำแหง สาขาวิทยบริการเฉลิมพระเกียรติจังหวัดสงขลา', 'Ramkhamhaeng University — Academic Services Branch, Songkhla (00718)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-00719', 'มหาวิทยาลัยรามคำแหง สาขาวิทยบริการเฉลิมพระเกียรติจังหวัดสุโขทัย', 'Ramkhamhaeng University — Academic Services Branch, Sukhothai (00719)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-00720', 'มหาวิทยาลัยรามคำแหง สาขาวิทยบริการเฉลิมพระเกียรติจังหวัดสุรินทร์', 'Ramkhamhaeng University — Academic Services Branch, Surin (00720)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-00721', 'มหาวิทยาลัยรามคำแหง สาขาวิทยบริการเฉลิมพระเกียรติจังหวัดหนองบัวลำภู', 'Ramkhamhaeng University — Academic Services Branch, Nong Bua Lamphu (00721)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-00722', 'มหาวิทยาลัยรามคำแหง สาขาวิทยบริการเฉลิมพระเกียรติจังหวัดอำนาจเจริญ', 'Ramkhamhaeng University — Academic Services Branch, Amnat Charoen (00722)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-00723', 'มหาวิทยาลัยรามคำแหง สาขาวิทยบริการเฉลิมพระเกียรติจังหวัดอุดรธานี', 'Ramkhamhaeng University — Academic Services Branch, Udon Thani (00723)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-00724', 'มหาวิทยาลัยรามคำแหง สาขาวิทยบริการเฉลิมพระเกียรติจังหวัดอุทัยธานี', 'Ramkhamhaeng University — Academic Services Branch, Uthai Thani (00724)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-00800', 'มหาวิทยาลัยศิลปากร', 'Silpakorn University', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-00801', 'มหาวิทยาลัยศิลปากร วิทยาเขตพระราชวังสนามจันทร์', 'Silpakorn University — Campus, Nakhon Pathom (00801)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-00802', 'มหาวิทยาลัยศิลปากร วิทยาเขตสารสนเทศเพชรบุรี', 'Silpakorn University — Campus, Phetchaburi (00802)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-00803', 'มหาวิทยาลัยศิลปากร วิทยาเขตเมืองทองธานี', 'Silpakorn University — Campus, Nonthaburi (00803)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-00900', 'มหาวิทยาลัยศรีนครินทรวิโรฒ', 'Srinakharinwirot University', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-00901', 'มหาวิทยาลัยศรีนครินทรวิโรฒ องครักษ์', 'Srinakharinwirot University — Campus, Nakhon Nayok (00901)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-01000', 'มหาวิทยาลัยสงขลานครินทร์', 'Prince of Songkla University', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-01001', 'มหาวิทยาลัยสงขลานครินทร์ วิทยาเขตภูเก็ต', 'Prince of Songkla University — Campus, Phuket (01001)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-01002', 'มหาวิทยาลัยสงขลานครินทร์ วิทยาเขตสุราษฎร์ธานี', 'Prince of Songkla University — Campus, Surat Thani (01002)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-01003', 'มหาวิทยาลัยสงขลานครินทร์ วิทยาเขตปัตตานี', 'Prince of Songkla University — Campus, Pattani (01003)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-01004', 'มหาวิทยาลัยสงขลานครินทร์ วิทยาเขตตรัง', 'Prince of Songkla University — Campus, Trang (01004)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-01100', 'มหาวิทยาลัยสุโขทัยธรรมาธิราช', 'Sukhothai Thammathirat Open University', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-01101', 'มหาวิทยาลัยสุโขทัยธรรมาธิราช (ศูนย์วิทยบริการและชุมชนสัมพันธ์ มสธ. นนทบุรี)', 'Sukhothai Thammathirat Open University — Education Center, Nonthaburi (01101)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-01102', 'มหาวิทยาลัยสุโขทัยธรรมาธิราช (ศูนย์วิทยบริการและชุมชนสัมพันธ์ มสธ. ลำปาง)', 'Sukhothai Thammathirat Open University — Education Center, Lampang (01102)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-01103', 'มหาวิทยาลัยสุโขทัยธรรมาธิราช (ศูนย์วิทยบริการและชุมชนสัมพันธ์ มสธ. สุโขทัย)', 'Sukhothai Thammathirat Open University — Education Center, Sukhothai (01103)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-01104', 'มหาวิทยาลัยสุโขทัยธรรมาธิราช (ศูนย์วิทยบริการและชุมชนสัมพันธ์ มสธ. นครสวรรค์)', 'Sukhothai Thammathirat Open University — Education Center, Nakhon Sawan (01104)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-01105', 'มหาวิทยาลัยสุโขทัยธรรมาธิราช (ศูนย์วิทยบริการและชุมชนสัมพันธ์ มสธ. อุดรธานี)', 'Sukhothai Thammathirat Open University — Education Center, Udon Thani (01105)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-01106', 'มหาวิทยาลัยสุโขทัยธรรมาธิราช (ศูนย์วิทยบริการและชุมชนสัมพันธ์ มสธ. อุบลราชธานี)', 'Sukhothai Thammathirat Open University — Education Center, Ubon Ratchathani (01106)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-01107', 'มหาวิทยาลัยสุโขทัยธรรมาธิราช (ศูนย์วิทยบริการและชุมชนสัมพันธ์ มสธ. นครนายก)', 'Sukhothai Thammathirat Open University — Education Center, Nakhon Nayok (01107)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-01108', 'มหาวิทยาลัยสุโขทัยธรรมาธิราช (ศูนย์วิทยบริการและชุมชนสัมพันธ์ มสธ. เพชรบุรี)', 'Sukhothai Thammathirat Open University — Education Center, Phetchaburi (01108)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-01109', 'มหาวิทยาลัยสุโขทัยธรรมาธิราช (ศูนย์วิทยบริการและชุมชนสัมพันธ์ มสธ. จันทบุรี)', 'Sukhothai Thammathirat Open University — Education Center, Chanthaburi (01109)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-01110', 'มหาวิทยาลัยสุโขทัยธรรมาธิราช (ศูนย์วิทยบริการและชุมชนสัมพันธ์ มสธ. นครศรีธรรมราช)', 'Sukhothai Thammathirat Open University — Education Center, Nakhon Si Thammarat (01110)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-01111', 'มหาวิทยาลัยสุโขทัยธรรมาธิราช (ศูนย์วิทยบริการและชุมชนสัมพันธ์ มสธ. ยะลา)', 'Sukhothai Thammathirat Open University — Education Center, Yala (01111)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-01200', 'สถาบันบัณฑิตพัฒนบริหารศาสตร์', 'National Institute of Development Administration', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-01201', 'สถาบันบัณฑิตพัฒนบริหารศาสตร์ วิทยาเขตชลบุรี', 'National Institute of Development Administration — Campus, Chon Buri (01201)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-01202', 'สถาบันบัณฑิตพัฒนบริหารศาสตร์ วิทยาเขตนครราชสีมา', 'National Institute of Development Administration — Campus, Nakhon Ratchasima (01202)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-01203', 'สถาบันบัณฑิตพัฒนบริหารศาสตร์ วิทยาเขตอุบลราชธานี', 'National Institute of Development Administration — Campus, Ubon Ratchathani (01203)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-01204', 'สถาบันบัณฑิตพัฒนบริหารศาสตร์ วิทยาเขตอุดรธานี', 'National Institute of Development Administration — Campus, Udon Thani (01204)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-01205', 'สถาบันบัณฑิตพัฒนบริหารศาสตร์ วิทยาเขตลำพูน', 'National Institute of Development Administration — Campus, Lamphun (01205)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-01206', 'สถาบันบัณฑิตพัฒนบริหารศาสตร์ วิทยาเขตเชียงราย', 'National Institute of Development Administration — Campus, Chiang Rai (01206)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-01207', 'สถาบันบัณฑิตพัฒนบริหารศาสตร์ วิทยาเขตพิษณุโลก', 'National Institute of Development Administration — Campus, Phitsanulok (01207)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-01208', 'สถาบันบัณฑิตพัฒนบริหารศาสตร์ วิทยาเขตภูเก็ต', 'National Institute of Development Administration — Campus, Phuket (01208)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-01209', 'สถาบันบัณฑิตพัฒนบริหารศาสตร์ วิทยาเขตสุราษฎร์ธานี', 'National Institute of Development Administration — Campus, Surat Thani (01209)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-01210', 'สถาบันบัณฑิตพัฒนบริหารศาสตร์ วิทยาเขตหาดใหญ่', 'National Institute of Development Administration — Campus, Songkhla (01210)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-01211', 'สถาบันบัณฑิตพัฒนบริหารศาสตร์ วิทยาเขตยะลา', 'National Institute of Development Administration — Campus, Yala (01211)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-01212', 'สถาบันบัณฑิตพัฒนบริหารศาสตร์ จังหวัดระยอง', 'National Institute of Development Administration — Campus, Rayong (01212)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-01300', 'มหาวิทยาลัยแม่โจ้', 'Maejo University', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-01301', 'มหาวิทยาลัยแม่โจ้ - แพร่ ฉลิมพระเกียรติ', 'Maejo University — Campus, Phrae (01301)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-01302', 'มหาวิทยาลัยแม่โจ้ - ชุมพร', 'Maejo University — Campus, Chumphon (01302)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-01400', 'มหาวิทยาลัยเทคโนโลยีพระจอมเกล้าธนบุรี', 'King Mongkut''s University of Technology Thonburi', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-01401', 'มหาวิทยาลัยเทคโนโลยีพระจอมเกล้าธนบุรี วิทยาเขตราชบุรี', 'King Mongkut''s University of Technology Thonburi — Campus, Ratchaburi (01401)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-01402', 'มหาวิทยาลัยเทคโนโลยีพระจอมเกล้าธนบุรี วิทยาเขตบางขุนเทียน', 'King Mongkut''s University of Technology Thonburi — Campus, Bangkok (01402)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-01500', 'มหาวิทยาลัยเทคโนโลยีพระจอมเกล้าพระนครเหนือ', 'King Mongkut''s University of Technology North Bangkok', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-01501', 'มหาวิทยาลัยเทคโนโลยีพระจอมเกล้าพระนครเหนือ วิทยาเขตปราจีนบุรี', 'King Mongkut''s University of Technology North Bangkok — Campus, Prachin Buri (01501)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-01502', 'มหาวิทยาลัยเทคโนโลยีพระจอมเกล้าพระนครเหนือ วิทยาเขตระยอง', 'King Mongkut''s University of Technology North Bangkok — Campus, Rayong (01502)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-01600', 'สถาบันเทคโนโลยีพระจอมเกล้าเจ้าคุณทหารลาดกระบัง', 'King Mongkut''s Institute of Technology Ladkrabang', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-01601', 'สถาบันเทคโนโลยีพระจอมเกล้าเจ้าคุณทหารลาดกระบัง วิทยาเขตชุมพรเขตอุดมศักดิ์', 'King Mongkut''s Institute of Technology Ladkrabang — Campus, Chumphon (01601)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-01700', 'มหาวิทยาลัยเทคโนโลยีสุรนารี', 'Suranaree University of Technology', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-01800', 'มหาวิทยาลัยอุบลราชธานี', 'Ubon Ratchathani University', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-01802', 'มหาวิทยาลัยอุบลราชธานี วิทยาเขตมุกดาหาร', 'Ubon Ratchathani University — Campus, Mukdahan (01802)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-01900', 'มหาวิทยาลัยบูรพา', 'Burapha University', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-01901', 'มหาวิทยาลัยบูรพา วิทยาเขตสารสนเทศจันทบุรี', 'Burapha University — Campus, Chanthaburi (01901)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-01902', 'มหาวิทยาลัยบูรพา วิทยาเขตสารสนเทศสระแก้ว', 'Burapha University — Campus, Sa Kaeo (01902)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-02000', 'มหาวิทยาลัยนเรศวร', 'Naresuan University', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-02100', 'มหาวิทยาลัยมหาสารคาม', 'Mahasarakham University', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-02200', 'มหาวิทยาลัยทักษิณ', 'Thaksin University', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-02201', 'มหาวิทยาลัยทักษิณ วิทยาเขตพัทลุง', 'Thaksin University — Campus, Phatthalung (02201)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-02202', 'มหาวิทยาลัยทักษิณ วิทยาเขตสงขลา', 'Thaksin University — Campus, Songkhla (02202)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-02300', 'มหาวิทยาลัยวลัยลักษณ์', 'Walailak University', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-02400', 'มหาวิทยาลัยแม่ฟ้าหลวง', 'Mae Fah Luang University', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-02500', 'มหาวิทยาลัยนราธิวาสราชนครินทร์', 'Princess of Naradhiwas University', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-02600', 'มหาวิทยาลัยนครพนม', 'Nakhon Phanom University', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-02700', 'มหาวิทยาลัยพะเยา', 'University of Phayao', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-05100', 'มหาวิทยาลัยกรุงเทพ', 'Bangkok University', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-05101', 'มหาวิทยาลัยกรุงเทพ วิทยาเขตรังสิต', 'Bangkok University — Campus, Pathum Thani (05101)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-05300', 'มหาวิทยาลัยพายัพ', 'Payap University', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-05400', 'มหาวิทยาลัยศรีปทุม', 'Sripatum University', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-05401', 'มหาวิทยาลัยศรีปทุม วิทยาเขตชลบุรี', 'Sripatum University — Campus, Chon Buri (05401)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-05402', 'มหาวิทยาลัยศรีปทุม วิทยาเขตขอนแก่น', 'Sripatum University — Campus, Khon Kaen (05402)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-05600', 'มหาวิทยาลัยหอการค้าไทย', 'University of the Thai Chamber of Commerce', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-05700', 'มหาวิทยาลัยเกริก', 'Krirk University', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-05900', 'มหาวิทยาลัยคริสเตียน', 'Christian University of Thailand', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-06000', 'มหาวิทยาลัยเซนต์จอห์น', 'Saint John''s University', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-06100', 'มหาวิทยาลัยเทคโนโลยีมหานคร', 'Mahanakorn University of Technology', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-06800', 'มหาวิทยาลัยรังสิต', 'Rangsit University', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-07300', 'มหาวิทยาลัยหัวเฉียวเฉลิมพระเกียรติ', 'Huachiew Chalermprakiet University', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-07400', 'มหาวิทยาลัยอัสสัมชัญ', 'Assumption University of Thailand', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-07401', 'มหาวิทยาลัยอัสสัมชัญ วิทยาเขตสุวรรณภูมิ', 'Assumption University of Thailand — Campus, Samut Prakan (07401)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-08300', 'มหาวิทยาลัยราชธานี', 'Ratchathani University', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-08301', 'มหาวิทยาลัยราชธานี วิทยาเขตอุดรธานี', 'Ratchathani University — Campus, Udon Thani (08301)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-09000', 'มหาวิทยาลัยธนบุรี', 'Thonburi University', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-09001', 'มหาวิทยาลัยธนบุรี วิทยาเขตภาคเหนือ จังหวัดลำพูน', 'Thonburi University — Campus, Lamphun (09001)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-10000', 'มหาวิทยาลัยเจ้าพระยา', 'Chaopraya University', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-10100', 'มหาวิทยาลัยชินวัตร', 'Shinawatra University', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-10200', 'มหาวิทยาลัยเวสเทิร์น', 'Western University', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-10201', 'มหาวิทยาลัยเวสเทิร์น วัชรพล', 'Western University — Campus, Pathum Thani (10201)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-10202', 'มหาวิทยาลัยเวสเทิร์น บุรีรัมย์', 'Western University — Campus, Buriram (10202)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-10203', 'มหาวิทยาลัยเวสเทิร์น กาญจนบุรี', 'Western University — Campus, Kanchanaburi (10203)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-10300', 'มหาวิทยาลัยธุรกิจบัณฑิตย์', 'Dhurakij Pundit University', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-10400', 'มหาวิทยาลัยภาคตะวันออกเฉียงเหนือ', 'Northeastern University', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-10500', 'มหาวิทยาลัยฟาร์อีสเทอร์น', 'The Far Eastern University', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-10600', 'มหาวิทยาลัยภาคกลาง', 'The University of Central Thailand', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-10700', 'มหาวิทยาลัยวงษ์ชวลิตกุล', 'Vongchavalitkul University', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-11000', 'วิทยาลัยสันตพล', 'Santapol College', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-11100', 'มหาวิทยาลัยเอเชียอาคเนย์', 'South-East Asia University', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-11200', 'มหาวิทยาลัยอีสเทิร์นเอเชีย', 'Eastern Asia University', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-11300', 'มหาวิทยาลัยกรุงเทพธนบุรี', 'Bangkok Thonburi University', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-11400', 'มหาวิทยาลัยนานาชาติเซนต์เทเรซา', 'St Theresa International University', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-11500', 'วิทยาลัยเซนต์หลุยส์', 'Saint Louis College', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-11600', 'มหาวิทยาลัยเซาธ์อีสท์บางกอก', 'Southeast Bangkok University', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-11700', 'วิทยาลัยดุสิตธานี', 'Dusit Thani College', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-11701', 'วิทยาลัยดุสิตธานี ศูนย์การศึกษาเมืองพัทยา', 'Dusit Thani College — Education Center, Chon Buri (11701)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-11800', 'มหาวิทยาลัยตาปี', 'Tapee University', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-11900', 'วิทยาลัยทองสุข', 'Thongsook College', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-12000', 'วิทยาลัยเทคโนโลยีภาคใต้', 'Southern College of Technology', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-12200', 'มหาวิทยาลัยนอร์ทกรุงเทพ', 'North Bangkok University', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-12300', 'มหาวิทยาลัยนอร์ท-เชียงใหม่', 'North-Chiang Mai University', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-12400', 'มหาวิทยาลัยนานาชาติแสตมฟอร์ด', 'Stamford International University', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-12600', 'วิทยาลัยบัณฑิตเอเชีย', 'College of Asian Scholars', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-12700', 'มหาวิทยาลัยปทุมธานี', 'Pathumthani University', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-12800', 'มหาวิทยาลัยการจัดการและเทคโนโลยีอีสเทิร์น', 'The Eastern University of Management and Technology', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-12900', 'มหาวิทยาลัยนานาชาติเอเชีย-แปซิฟิก', 'Asia-Pacific International University', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-12901', 'มหาวิทยาลัยนานาชาติเอเชีย-แปซิฟิก วิทยาเขตกรุงเทพฯ', 'Asia-Pacific International University — Campus, Bangkok (12901)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-13000', 'มหาวิทยาลัยหาดใหญ่', 'Hatyai University', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-13100', 'มหาวิทยาลัยเนชั่น', 'Nation University', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-13200', 'สถาบันรัชต์ภาคย์', 'Rajapark Institute', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-13201', 'สถาบันรัชต์ภาคย์ วิทยาเขตยะลา', 'Rajapark Institute — Campus, Yala (13201)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-13300', 'มหาวิทยาลัยรัตนบัณฑิต', 'Rattana Bundit University', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-13301', 'มหาวิทยาลัยรัตนบัณฑิต วิทยาเขตปทุมธานี', 'Rattana Bundit University — Campus, Pathum Thani (13301)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-13400', 'วิทยาลัยนอร์ทเทิร์น', 'Northern College', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-13600', 'วิทยาลัยแสงธรรม', 'Saengtham College', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-13601', 'วิทยาลัยแสงธรรม วิทยาเขตเซเวียร์', 'Saengtham College — Campus, Chiang Rai (13601)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-13700', 'มหาวิทยาลัยฟาฏอนี', 'Fatoni University', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-13900', 'มหาวิทยาลัยราชภัฏกาญจนบุรี', 'Kanchanaburi Rajabhat University', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-14000', 'มหาวิทยาลัยกาฬสินธุ์', 'Kalasin University', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-14100', 'มหาวิทยาลัยราชภัฏกำแพงเพชร', 'Kamphaeng Phet Rajabhat University', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-14200', 'มหาวิทยาลัยราชภัฏชัยภูมิ', 'Chaiyaphum Rajabhat University', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-14300', 'มหาวิทยาลัยราชภัฏเชียงราย', 'Chiang Rai Rajabhat University', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-14400', 'มหาวิทยาลัยราชภัฏเชียงใหม่', 'Chiang Mai Rajabhat University', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-14401', 'มหาวิทยาลัยราชภัฏเชียงใหม่ วิทยาเขตแม่ฮ่องสอน', 'Chiang Mai Rajabhat University — Campus, Mae Hong Son (14401)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-14500', 'มหาวิทยาลัยราชภัฏเทพสตรี', 'Thepsatri Rajabhat University', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-14600', 'มหาวิทยาลัยราชภัฏธนบุรี', 'Dhonburi Rajabhat University', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-14700', 'มหาวิทยาลัยราชภัฏนครปฐม', 'Nakhon Pathom Rajabhat University', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-14800', 'มหาวิทยาลัยราชภัฏนครราชสีมา', 'Nakhon Ratchasima Rajabhat University', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-14900', 'มหาวิทยาลัยราชภัฏนครศรีธรรมราช', 'Nakhon Si Thammarat Rajabhat University', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-15000', 'มหาวิทยาลัยราชภัฏพระนคร', 'Phranakhon Rajabhat University', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-15100', 'มหาวิทยาลัยราชภัฏพระนครศรีอยุธยา', 'Phranakhon Si Ayutthaya Rajabhat University', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-15200', 'มหาวิทยาลัยราชภัฏพิบูลสงคราม', 'Pibulsongkram Rajabhat University', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-15300', 'มหาวิทยาลัยราชภัฏวไลยอลงกรณ์ ในพระบรมราชูปถัมภ์', 'Valaya Alongkorn Rajabhat University under the Royal Patronage', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-15400', 'มหาวิทยาลัยราชภัฏเพชรบูรณ์', 'Phetchabun Rajabhat University', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-15500', 'มหาวิทยาลัยราชภัฏภูเก็ต', 'Phuket Rajabhat University', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-15600', 'มหาวิทยาลัยราชภัฏมหาสารคาม', 'Rajabhat Maha Sarakham University', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-15700', 'มหาวิทยาลัยราชภัฏยะลา', 'Yala Rajabhat University', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-15800', 'มหาวิทยาลัยราชภัฏร้อยเอ็ด', 'Roi Et Rajabhat University', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-15900', 'มหาวิทยาลัยราชภัฏราชนครินทร์', 'Rajabhat Rajanagarindra University', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-16000', 'มหาวิทยาลัยราชภัฏรำไพพรรณี', 'Rambhai Barni Rajabhat University', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-16100', 'มหาวิทยาลัยราชภัฏลำปาง', 'Lampang Rajabhat University', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-16200', 'มหาวิทยาลัยราชภัฏเลย', 'Loei Rajabhat University', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-16300', 'มหาวิทยาลัยราชภัฏศรีสะเกษ', 'Sisaket Rajabhat University', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-16400', 'มหาวิทยาลัยราชภัฏสงขลา', 'Songkhla Rajabhat University', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-16401', 'มหาวิทยาลัยราชภัฏสงขลา วิทยาเขตสตูล', 'Songkhla Rajabhat University — Campus, Satun (16401)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-16500', 'มหาวิทยาลัยสวนดุสิต', 'Suan Dusit University', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-16501', 'มหาวิทยาลัยสวนดุสิต วิทยาเขตสุพรรณบุรี', 'Suan Dusit University — Campus, Suphan Buri (16501)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-16502', 'มหาวิทยาลัยสวนดุสิต ศูนย์การศึกษา ลำปาง', 'Suan Dusit University — Education Center, Lampang (16502)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-16503', 'มหาวิทยาลัยสวนดุสิต ศูนย์การศึกษา นครนายก', 'Suan Dusit University — Education Center, Nakhon Nayok (16503)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-16504', 'มหาวิทยาลัยสวนดุสิต ศูนย์การศึกษา ตรัง', 'Suan Dusit University — Education Center, Trang (16504)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-16505', 'มหาวิทยาลัยสวนดุสิต ศูนย์การศึกษา หัวหิน', 'Suan Dusit University — Education Center, Prachuap Khiri Khan (16505)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-16600', 'มหาวิทยาลัยราชภัฏสวนสุนันทา', 'Suan Sunandha Rajabhat University', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-16601', 'มหาวิทยาลัยราชภัฏสวนสุนันทา วิทยาเขตนครปฐม', 'Suan Sunandha Rajabhat University — Campus, Nakhon Pathom (16601)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-16602', 'มหาวิทยาลัยราชภัฏสวนสุนันทา วิทยาเขตสมุทรสงคราม', 'Suan Sunandha Rajabhat University — Campus, Samut Songkhram (16602)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-16603', 'มหาวิทยาลัยราชภัฏสวนสุนันทา ศูนย์การศึกษาจังหวัดระนอง', 'Suan Sunandha Rajabhat University — Education Center, Ranong (16603)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-16604', 'มหาวิทยาลัยราชภัฏสวนสุนันทา ศูนย์การศึกษาจังหวัดอุดรธานี', 'Suan Sunandha Rajabhat University — Education Center, Udon Thani (16604)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-16700', 'มหาวิทยาลัยราชภัฏสุรินทร์', 'Surindra Rajabhat University', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-16800', 'มหาวิทยาลัยราชภัฏหมู่บ้านจอมบึง', 'Muban Chombueng Rajabhat University', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-16900', 'มหาวิทยาลัยราชภัฏอุดรธานี', 'Udon Thani Rajabhat University', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-16901', 'มหาวิทยาลัยราชภัฏอุดรธานี ศูนย์การศึกษาบึงกาฬ', 'Udon Thani Rajabhat University — Education Center, Bueng Kan (16901)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-17000', 'มหาวิทยาลัยราชภัฏอุตรดิตถ์', 'Uttaradit Rajabhat University', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-17100', 'มหาวิทยาลัยราชภัฏอุบลราชธานี', 'Ubon Ratchathani Rajabhat University', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-17200', 'มหาวิทยาลัยราชภัฏนครสวรรค์', 'Nakhon Sawan Rajabhat University', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-17300', 'มหาวิทยาลัยราชภัฏสุราษฏร์ธานี', 'Suratthani Rajabhat University', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-17400', 'มหาวิทยาลัยราชภัฏบ้านสมเด็จเจ้าพระยา', 'Bansomdejchaopraya Rajabhat University', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-17500', 'มหาวิทยาลัยราชภัฏสกลนคร', 'Sakon Nakhon Rajabhat University', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-17600', 'มหาวิทยาลัยราชภัฏบุรีรัมย์', 'Buriram Rajabhat University', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-17700', 'มหาวิทยาลัยราชภัฏจันทรเกษม', 'Chandrakasem Rajabhat University', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-17900', 'มหาวิทยาลัยราชภัฏเพชรบุรี', 'Phetchaburi Rajabhat University', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-18000', 'มหาวิทยาลัยเกษมบัณฑิต', 'Kasem Bundit University', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-18001', 'มหาวิทยาลัยเกษมบัณฑิต พัฒนาการ', 'Kasem Bundit University — Campus, Bangkok (18001)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-18100', 'มหาวิทยาลัยสยาม', 'Siam University', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-18200', 'วิทยาลัยเชียงราย', 'Chiangrai College', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-18300', 'มหาวิทยาลัยพิษณุโลก', 'Phitsanulok University', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-18400', 'วิทยาลัยพุทธศาสนานานาชาติ', 'International Buddhist College', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-18500', 'มหาวิทยาลัยมหาจุฬาลงกรณราชวิทยาลัย', 'Mahachulalongkornrajavidyalaya University', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-18501', 'มหาวิทยาลัยมหาจุฬาลงกรณราชวิทยาลัย วิทยาเขตหนองคาย', 'Mahachulalongkornrajavidyalaya University — Campus, Nong Khai (18501)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-18502', 'มหาวิทยาลัยมหาจุฬาลงกรณราชวิทยาลัย วิทยาเขตนครศรีธรรมราช', 'Mahachulalongkornrajavidyalaya University — Campus, Nakhon Si Thammarat (18502)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-18503', 'มหาวิทยาลัยมหาจุฬาลงกรณราชวิทยาลัย วิทยาเขตเชียงใหม่', 'Mahachulalongkornrajavidyalaya University — Campus, Chiang Mai (18503)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-18504', 'มหาวิทยาลัยมหาจุฬาลงกรณราชวิทยาลัย วิทยาเขตขอนแก่น', 'Mahachulalongkornrajavidyalaya University — Campus, Khon Kaen (18504)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-18505', 'มหาวิทยาลัยมหาจุฬาลงกรณราชวิทยาลัย วิทยาเขตนครราชสีมา', 'Mahachulalongkornrajavidyalaya University — Campus, Nakhon Ratchasima (18505)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-18506', 'มหาวิทยาลัยมหาจุฬาลงกรณราชวิทยาลัย วิทยาเขตอุบลราชธานี', 'Mahachulalongkornrajavidyalaya University — Campus, Ubon Ratchathani (18506)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-18507', 'มหาวิทยาลัยมหาจุฬาลงกรณราชวิทยาลัย วิทยาเขตแพร่', 'Mahachulalongkornrajavidyalaya University — Campus, Phrae (18507)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-18508', 'มหาวิทยาลัยมหาจุฬาลงกรณราชวิทยาลัย วิทยาเขตสุรินทร์', 'Mahachulalongkornrajavidyalaya University — Campus, Surin (18508)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-18509', 'มหาวิทยาลัยมหาจุฬาลงกรณราชวิทยาลัย วิทยาเขตพะเยา', 'Mahachulalongkornrajavidyalaya University — Campus, Phayao (18509)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-18510', 'มหาวิทยาลัยมหาจุฬาลงกรณราชวิทยาลัย วิทยาเขตบาฬีศึกษาพุทธโฆส', 'Mahachulalongkornrajavidyalaya University — Campus, Nakhon Pathom (18510)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-18512', 'มหาวิทยาลัยมหาจุฬาลงกรณราชวิทยาลัย วิทยาลัยสงฆ์นครพนม', 'Mahachulalongkornrajavidyalaya University — Buddhist College, Nakhon Phanom (18512)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-18513', 'มหาวิทยาลัยมหาจุฬาลงกรณราชวิทยาลัย วิทยาลัยสงฆ์เลย', 'Mahachulalongkornrajavidyalaya University — Buddhist College, Loei (18513)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-18514', 'มหาวิทยาลัยมหาจุฬาลงกรณราชวิทยาลัย วิทยาลัยสงฆ์ลำพูน', 'Mahachulalongkornrajavidyalaya University — Buddhist College, Lamphun (18514)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-18515', 'มหาวิทยาลัยมหาจุฬาลงกรณราชวิทยาลัย วิทยาเขตนครสวรรค์', 'Mahachulalongkornrajavidyalaya University — Campus, Nakhon Sawan (18515)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-18516', 'มหาวิทยาลัยมหาจุฬาลงกรณราชวิทยาลัย วิทยาลัยสงฆ์พุทธชินราช', 'Mahachulalongkornrajavidyalaya University — Buddhist College, Phitsanulok (18516)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-18517', 'มหาวิทยาลัยมหาจุฬาลงกรณราชวิทยาลัย วิทยาลัยสมทบ', 'Mahachulalongkornrajavidyalaya University — Affiliated College, Bangkok (18517)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-18518', 'มหาวิทยาลัยมหาจุฬาลงกรณราชวิทยาลัย วิทยาลัยสงฆ์บุรีรัมย์', 'Mahachulalongkornrajavidyalaya University — Buddhist College, Buriram (18518)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-18519', 'มหาวิทยาลัยมหาจุฬาลงกรณราชวิทยาลัย วิทยาลัยสงฆ์ปัตตานี', 'Mahachulalongkornrajavidyalaya University — Buddhist College, Pattani (18519)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-18520', 'มหาวิทยาลัยมหาจุฬาลงกรณราชวิทยาลัย วิทยาลัยสงฆ์นครน่านเฉลิมพระเกียรติฯ', 'Mahachulalongkornrajavidyalaya University — Buddhist College, Nan (18520)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-18521', 'มหาวิทยาลัยมหาจุฬาลงกรณราชวิทยาลัย วิทยาลัยสงฆ์นครลำปาง', 'Mahachulalongkornrajavidyalaya University — Buddhist College, Lampang (18521)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-18522', 'มหาวิทยาลัยมหาจุฬาลงกรณราชวิทยาลัย วิทยาลัยสงฆ์พุทธโสธร ฉะเชิงเทรา', 'Mahachulalongkornrajavidyalaya University — Buddhist College, Chachoengsao (18522)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-18523', 'มหาวิทยาลัยมหาจุฬาลงกรณราชวิทยาลัย วิทยาลัยสงฆ์ศรีสะเกษ', 'Mahachulalongkornrajavidyalaya University — Buddhist College, Sisaket (18523)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-18524', 'มหาวิทยาลัยมหาจุฬาลงกรณราชวิทยาลัย วิทยาลัยสงฆ์เชียงราย', 'Mahachulalongkornrajavidyalaya University — Buddhist College, Chiang Rai (18524)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-18525', 'มหาวิทยาลัยมหาจุฬาลงกรณราชวิทยาลัย วิทยาลัยสงฆ์ร้อยเอ็ด', 'Mahachulalongkornrajavidyalaya University — Buddhist College, Roi Et (18525)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-18526', 'มหาวิทยาลัยมหาจุฬาลงกรณราชวิทยาลัย วิทยาลัยสงฆ์ชัยภูมิ', 'Mahachulalongkornrajavidyalaya University — Buddhist College, Chaiyaphum (18526)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-18527', 'มหาวิทยาลัยมหาจุฬาลงกรณราชวิทยาลัย วิทยาลัยสงฆ์พิจิตร', 'Mahachulalongkornrajavidyalaya University — Buddhist College, Phichit (18527)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-18528', 'มหาวิทยาลัยมหาจุฬาลงกรณราชวิทยาลัย วิทยาลัยสงฆ์สุพรรณบุรีศรีสุวรรณภูมิ', 'Mahachulalongkornrajavidyalaya University — Buddhist College, Suphan Buri (18528)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-18529', 'มหาวิทยาลัยมหาจุฬาลงกรณราชวิทยาลัย วิทยาลัยสงฆ์ระยอง', 'Mahachulalongkornrajavidyalaya University — Buddhist College, Rayong (18529)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-18530', 'มหาวิทยาลัยมหาจุฬาลงกรณราชวิทยาลัย วิทยาลัยสงฆ์มหาสารคาม', 'Mahachulalongkornrajavidyalaya University — Buddhist College, Maha Sarakham (18530)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-18531', 'มหาวิทยาลัยมหาจุฬาลงกรณราชวิทยาลัย วิทยาลัยสงฆ์สุราษฎร์ธานี', 'Mahachulalongkornrajavidyalaya University — Buddhist College, Surat Thani (18531)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-18532', 'มหาวิทยาลัยมหาจุฬาลงกรณราชวิทยาลัย วิทยาลัยสงฆ์อุทัยธานี', 'Mahachulalongkornrajavidyalaya University — Buddhist College, Uthai Thani (18532)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-18533', 'มหาวิทยาลัยมหาจุฬาลงกรณราชวิทยาลัย วิทยาลัยสงฆ์เพชรบุรี', 'Mahachulalongkornrajavidyalaya University — Buddhist College, Phetchaburi (18533)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-18534', 'มหาวิทยาลัยมหาจุฬาลงกรณราชวิทยาลัย วิทยาลัยสงฆ์ราชบุรี', 'Mahachulalongkornrajavidyalaya University — Buddhist College, Ratchaburi (18534)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-18535', 'มหาวิทยาลัยมหาจุฬาลงกรณราชวิทยาลัย วิทยาลัยสงฆ์พุทธปัญญาศรีทวารวดี นครปฐม', 'Mahachulalongkornrajavidyalaya University — Buddhist College, Nakhon Pathom (18535)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-18536', 'มหาวิทยาลัยมหาจุฬาลงกรณราชวิทยาลัย วิทยาลัยสงฆ์พ่อขุนผาเมือง เพชรบูรณ์', 'Mahachulalongkornrajavidyalaya University — Buddhist College, Phetchabun (18536)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-18537', 'มหาวิทยาลัยมหาจุฬาลงกรณราชวิทยาลัย วิทยาลัยสงฆ์ชลบุรี', 'Mahachulalongkornrajavidyalaya University — Buddhist College, Chon Buri (18537)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-18538', 'มหาวิทยาลัยมหาจุฬาลงกรณราชวิทยาลัย วิทยาลัยสงฆ์กาญจนบุรี ศรีไพบูลย์', 'Mahachulalongkornrajavidyalaya University — Buddhist College, Kanchanaburi (18538)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-18539', 'มหาวิทยาลัยมหาจุฬาลงกรณราชวิทยาลัย วิทยาลัยสงฆ์จันทบุรี', 'Mahachulalongkornrajavidyalaya University — Buddhist College, Chanthaburi (18539)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-18540', 'มหาวิทยาลัยมหาจุฬาลงกรณราชวิทยาลัย วิทยาลัยสงฆ์กำแพงเพชร', 'Mahachulalongkornrajavidyalaya University — Buddhist College, Kamphaeng Phet (18540)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-18541', 'มหาวิทยาลัยมหาจุฬาลงกรณราชวิทยาลัย วิทยาลัยสงฆ์ตาก', 'Mahachulalongkornrajavidyalaya University — Buddhist College, Tak (18541)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-18600', 'มหาวิทยาลัยมหามกุฏราชวิทยาลัย', 'Mahamakut Buddhist University', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-18601', 'มหาวิทยาลัยมหามกุฏราชวิทยาลัย วิทยาเขตมหาวชิราลงกรณราชวิทยาลัย', 'Mahamakut Buddhist University — Campus, Phra Nakhon Si Ayutthaya (18601)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-18602', 'มหาวิทยาลัยมหามกุฏราชวิทยาลัย วิทยาเขตร้อยเอ็ด', 'Mahamakut Buddhist University — Campus, Roi Et (18602)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-18603', 'มหาวิทยาลัยมหามกุฏราชวิทยาลัย วิทยาเขตล้านนา', 'Mahamakut Buddhist University — Campus, Chiang Mai (18603)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-18604', 'มหาวิทยาลัยมหามกุฏราชวิทยาลัย วิทยาเขตศรีธรรมาโศกราช', 'Mahamakut Buddhist University — Campus, Nakhon Si Thammarat (18604)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-18605', 'มหาวิทยาลัยมหามกุฏราชวิทยาลัย วิทยาเขตศรีล้านช้าง', 'Mahamakut Buddhist University — Campus, Khon Kaen (18605)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-18606', 'มหาวิทยาลัยมหามกุฏราชวิทยาลัย วิทยาเขตสิรินธรราชวิทยาลัย', 'Mahamakut Buddhist University — Campus, Nakhon Pathom (18606)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-18607', 'มหาวิทยาลัยมหามกุฏราชวิทยาลัย วิทยาเขตอีสาน', 'Mahamakut Buddhist University — Campus, Khon Kaen (18607)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-18608', 'มหาวิทยาลัยมหามกุฏราชวิทยาลัย มหาปชาบดีเถรีวิทยาลัย ในพระสังฆราชูปถัมภ์', 'Mahamakut Buddhist University — Campus, Nakhon Ratchasima (18608)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-18609', 'มหาวิทยาลัยมหามกุฏราชวิทยาลัย วิทยาลัยศาสนศาสตร์ยโสธร', 'Mahamakut Buddhist University — College of Religious Studies, Yasothon (18609)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-18610', 'มหาวิทยาลัยมหามกุฏราชวิทยาลัย วิทยาลัยศาสนศาสตร์เฉลิมพระเกียรติกาฬสินธุ์', 'Mahamakut Buddhist University — College of Religious Studies, Kalasin (18610)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-18611', 'มหาวิทยาลัยมหามกุฏราชวิทยาลัย วิทยาลัยศาสนศาสตร์นครราชสีมา', 'Mahamakut Buddhist University — College of Religious Studies, Nakhon Ratchasima (18611)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-18700', 'สถาบันเทคโนโลยีปทุมวัน', 'Pathumwan Institute of Technology', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-18800', 'วิทยาลัยนครราชสีมา', 'Nakhon Ratchasima College', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-19100', 'มหาวิทยาลัยเทคโนโลยีราชมงคลธัญบุรี', 'Rajamangala University of Technology Thanyaburi', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-19101', 'มหาวิทยาลัยเทคโนโลยีราชมงคลธัญบุรี วิทยาเขตปทุมธานี', 'Rajamangala University of Technology Thanyaburi — Campus, Pathum Thani (19101)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-19200', 'มหาวิทยาลัยเทคโนโลยีราชมงคลกรุงเทพ', 'Rajamangala University of Technology Krungthep', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-19201', 'มหาวิทยาลัยเทคโนโลยีราชมงคลกรุงเทพ วิทยาเขตเทคนิคกรุงเทพฯ', 'Rajamangala University of Technology Krungthep — Campus, Bangkok (19201)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-19202', 'มหาวิทยาลัยเทคโนโลยีราชมงคลกรุงเทพ วิทยาเขตบพิตรพิมุข มหาเมฆ', 'Rajamangala University of Technology Krungthep — Campus, Bangkok (19202)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-19203', 'มหาวิทยาลัยเทคโนโลยีราชมงคลกรุงเทพ วิทยาเขตพระนครใต้', 'Rajamangala University of Technology Krungthep — Campus, Bangkok (19203)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-19300', 'มหาวิทยาลัยเทคโนโลยีราชมงคลตะวันออก', 'Rajamangala University of Technology Tawan-Ok', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-19301', 'มหาวิทยาลัยเทคโนโลยีราชมงคลตะวันออก วิทยาเขตจักรพงษภูนารถ', 'Rajamangala University of Technology Tawan-Ok — Campus, Bangkok (19301)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-19302', 'มหาวิทยาลัยเทคโนโลยีราชมงคลตะวันออก วิทยาเขตอุเทนถวาย', 'Rajamangala University of Technology Tawan-Ok — Campus, Bangkok (19302)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-19303', 'มหาวิทยาลัยเทคโนโลยีราชมงคลตะวันออก วิทยาเขตบางพระ จังหวัดชลบุรี', 'Rajamangala University of Technology Tawan-Ok — Campus, Chon Buri (19303)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-19304', 'มหาวิทยาลัยเทคโนโลยีราชมงคลตะวันออก วิทยาเขตจันทบุรี', 'Rajamangala University of Technology Tawan-Ok — Campus, Chanthaburi (19304)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-19305', 'มหาวิทยาลัยเทคโนโลยีราชมงคลตะวันออก คณะเกษตรศาสตร์บางพระ จังหวัดชลบุรี', 'Rajamangala University of Technology Tawan-Ok — Campus, Chon Buri (19305)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-19400', 'มหาวิทยาลัยเทคโนโลยีราชมงคลพระนคร', 'Rajamangala University of Technology Phra Nakhon', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-19401', 'มหาวิทยาลัยเทคโนโลยีราชมงคลพระนคร ศูนย์เทเวศร์', 'Rajamangala University of Technology Phra Nakhon — Education Center, Bangkok (19401)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-19402', 'มหาวิทยาลัยเทคโนโลยีราชมงคลพระนคร ศูนย์โชติเวช', 'Rajamangala University of Technology Phra Nakhon — Education Center, Bangkok (19402)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-19403', 'มหาวิทยาลัยเทคโนโลยีราชมงคลพระนคร ศูนย์พณิชยการพระนคร', 'Rajamangala University of Technology Phra Nakhon — Education Center, Bangkok (19403)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-19405', 'มหาวิทยาลัยเทคโนโลยีราชมงคลพระนคร ศูนย์พระนครเหนือ', 'Rajamangala University of Technology Phra Nakhon — Education Center, Bangkok (19405)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-19500', 'มหาวิทยาลัยเทคโนโลยีราชมงคลรัตนโกสินทร์', 'Rajamangala University of Technology Rattanakosin', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-19501', 'มหาวิทยาลัยเทคโนโลยีราชมงคลรัตนโกสินทร์ วิทยาเขตเพาะช่าง', 'Rajamangala University of Technology Rattanakosin — Campus, Bangkok (19501)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-19502', 'มหาวิทยาลัยเทคโนโลยีราชมงคลรัตนโกสินทร์ วิทยาเขตบพิตรพิมุข จักรวรรดิ', 'Rajamangala University of Technology Rattanakosin — Campus, Bangkok (19502)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-19503', 'มหาวิทยาลัยเทคโนโลยีราชมงคลรัตนโกสินทร์ วิทยาเขตศาลายา', 'Rajamangala University of Technology Rattanakosin — Campus, Nakhon Pathom (19503)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-19504', 'มหาวิทยาลัยเทคโนโลยีราชมงคลรัตนโกสินทร์ วิทยาเขตวังไกลกังวล', 'Rajamangala University of Technology Rattanakosin — Campus, Prachuap Khiri Khan (19504)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-19600', 'มหาวิทยาลัยเทคโนโลยีราชมงคลล้านนา', 'Rajamangala University of Technology Lanna', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-19601', 'มหาวิทยาลัยเทคโนโลยีราชมงคลล้านนา วิทยาเขตภาคพายัพจังหวัดเชียงใหม่', 'Rajamangala University of Technology Lanna — Campus, Chiang Mai (19601)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-19602', 'มหาวิทยาลัยเทคโนโลยีราชมงคลล้านนา วิทยาเขตน่าน', 'Rajamangala University of Technology Lanna — Campus, Nan (19602)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-19603', 'มหาวิทยาลัยเทคโนโลยีราชมงคลล้านนา วิทยาเขตลำปาง', 'Rajamangala University of Technology Lanna — Campus, Lampang (19603)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-19604', 'มหาวิทยาลัยเทคโนโลยีราชมงคลล้านนา วิทยาเขตเชียงราย', 'Rajamangala University of Technology Lanna — Campus, Chiang Rai (19604)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-19605', 'มหาวิทยาลัยเทคโนโลยีราชมงคลล้านนา วิทยาเขตตาก', 'Rajamangala University of Technology Lanna — Campus, Tak (19605)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-19606', 'มหาวิทยาลัยเทคโนโลยีราชมงคลล้านนา วิทยาเขตพิษณุโลก', 'Rajamangala University of Technology Lanna — Campus, Phitsanulok (19606)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-19607', 'มหาวิทยาลัยเทคโนโลยีราชมงคลล้านนา สถาบันวิจัยและฝึกอบรมการเกษตรลำปาง', 'Rajamangala University of Technology Lanna — Campus, Lampang (19607)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-19700', 'มหาวิทยาลัยเทคโนโลยีราชมงคลศรีวิชัย', 'Rajamangala University of Technology Srivijaya', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-19701', 'มหาวิทยาลัยเทคโนโลยีราชมงคลศรีวิชัย วิทยาเขตสงขลา', 'Rajamangala University of Technology Srivijaya — Campus, Songkhla (19701)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-19702', 'มหาวิทยาลัยเทคโนโลยีราชมงคลศรีวิชัย วิทยาเขตนครศรีธรรมราช (พื้นที่ไสใหญ่)', 'Rajamangala University of Technology Srivijaya — Campus, Nakhon Si Thammarat (19702)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-19703', 'มหาวิทยาลัยเทคโนโลยีราชมงคลศรีวิชัย วิทยาเขตตรัง', 'Rajamangala University of Technology Srivijaya — Campus, Trang (19703)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-19704', 'มหาวิทยาลัยเทคโนโลยีราชมงคลศรีวิชัย วิทยาเขตนครศรีธรรมราช (พื้นที่ทุ่งใหญ่)', 'Rajamangala University of Technology Srivijaya — Campus, Nakhon Si Thammarat (19704)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-19705', 'มหาวิทยาลัยเทคโนโลยีราชมงคลศรีวิชัย วิทยาเขตนครศรีธรรมราช (พื้นที่ขนอม)', 'Rajamangala University of Technology Srivijaya — Campus, Nakhon Si Thammarat (19705)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-19800', 'มหาวิทยาลัยเทคโนโลยีราชมงคลสุวรรณภูมิ', 'Rajamangala University of Technology Suvarnabhumi', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-19801', 'มหาวิทยาลัยเทคโนโลยีราชมงคลสุวรรณภูมิ วิทยาเขตนนทบุรี', 'Rajamangala University of Technology Suvarnabhumi — Campus, Nonthaburi (19801)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-19802', 'มหาวิทยาลัยเทคโนโลยีราชมงคลสุวรรณภูมิ วิทยาเขตพระนครศรีอยุธยา วาสุกรี', 'Rajamangala University of Technology Suvarnabhumi — Campus, Phra Nakhon Si Ayutthaya (19802)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-19803', 'มหาวิทยาลัยเทคโนโลยีราชมงคลสุวรรณภูมิ วิทยาเขตพระนครศรีอยุธยา หันตรา', 'Rajamangala University of Technology Suvarnabhumi — Campus, Phra Nakhon Si Ayutthaya (19803)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-19804', 'มหาวิทยาลัยเทคโนโลยีราชมงคลสุวรรณภูมิ วิทยาเขตสุพรรณบุรี', 'Rajamangala University of Technology Suvarnabhumi — Campus, Suphan Buri (19804)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-19900', 'มหาวิทยาลัยเทคโนโลยีราชมงคลอีสาน', 'Rajamangala University of Technology Isan', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-19901', 'มหาวิทยาลัยเทคโนโลยีราชมงคลอีสาน นครราชสีมา', 'Rajamangala University of Technology Isan — Campus, Nakhon Ratchasima (19901)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-19902', 'มหาวิทยาลัยเทคโนโลยีราชมงคลอีสาน วิทยาเขตสุรินทร์', 'Rajamangala University of Technology Isan — Campus, Surin (19902)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-19903', 'มหาวิทยาลัยเทคโนโลยีราชมงคลอีสาน วิทยาเขตขอนแก่น', 'Rajamangala University of Technology Isan — Campus, Khon Kaen (19903)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-19905', 'มหาวิทยาลัยเทคโนโลยีราชมงคลอีสาน วิทยาเขตสกลนคร', 'Rajamangala University of Technology Isan — Campus, Sakon Nakhon (19905)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-20100', 'มหาวิทยาลัยเฉลิมกาญจนา ศรีสะเกษ', 'Chalermkarnchana University', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-20101', 'มหาวิทยาลัยเฉลิมกาญจนา วิทยาเขตระยอง', 'Chalermkarnchana University — Campus, Rayong (20101)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-20102', 'มหาวิทยาลัยเฉลิมกาญจนา สุรินทร์', 'Chalermkarnchana University — Campus, Surin (20102)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-20103', 'มหาวิทยาลัยเฉลิมกาญจนา บุรีรัมย์', 'Chalermkarnchana University — Campus, Buriram (20103)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-20104', 'มหาวิทยาลัยเฉลิมกาญจนา เพชรบูรณ์', 'Chalermkarnchana University — Campus, Phetchabun (20104)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-20105', 'มหาวิทยาลัยเฉลิมกาญจนา นครศรีธรรมราช', 'Chalermkarnchana University — Campus, Nakhon Si Thammarat (20105)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-20106', 'มหาวิทยาลัยเฉลิมกาญจนา ฉะเชิงเทรา', 'Chalermkarnchana University — Campus, Chachoengsao (20106)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-20200', 'วิทยาลัยอินเตอร์เทคลำปาง', 'Lampang Inter-Tech College', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-20300', 'สถาบันวิทยาลัยชุมชน', 'Institute of Community Colleges', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-20301', 'วิทยาลัยชุมชนแม่ฮ่องสอน', 'Mae Hong Son Community College', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-20302', 'วิทยาลัยชุมชนพิจิตร', 'Phichit Community College', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-20303', 'วิทยาลัยชุมชนตาก', 'Tak Community College', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-20304', 'วิทยาลัยชุมชนบุรีรัมย์', 'Buriram Community College', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-20305', 'วิทยาลัยชุมชนมุกดาหาร', 'Mukdahan Community College', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-20306', 'วิทยาลัยชุมชนหนองบัวลำภู', 'Nong Bua Lamphu Community College', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-20307', 'วิทยาลัยชุมชนสระแก้ว', 'Sa Kaeo Community College', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-20308', 'วิทยาลัยชุมชนอุทัยธานี', 'Uthai Thani Community College', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-20309', 'วิทยาลัยชุมชนระนอง', 'Ranong Community College', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-20310', 'วิทยาลัยชุมชนนราธิวาส', 'Narathiwat Community College', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-20311', 'วิทยาลัยชุมชนยะลา', 'Yala Community College', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-20312', 'วิทยาลัยชุมชนปัตตานี', 'Pattani Community College', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-20313', 'วิทยาลัยชุมชนสตูล', 'Satun Community College', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-20314', 'วิทยาลัยชุมชนสมุทรสาคร', 'Samut Sakhon Community College', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-20315', 'วิทยาลัยชุมชนยโสธร', 'Yasothon Community College', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-20316', 'วิทยาลัยชุมชนพังงา', 'Phang Nga Community College', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-20317', 'วิทยาลัยชุมชนตราด', 'Trat Community College', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-20318', 'วิทยาลัยชุมชนแพร่', 'Phrae Community College', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-20319', 'วิทยาลัยชุมชนสงขลา', 'Songkhla Community College', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-20320', 'วิทยาลัยชุมชนน่าน', 'Nan Community College', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-20321', 'วิทยาลัยชุมชนสุโขทัย', 'Sukhothai Community College', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-20400', 'โรงเรียนนายร้อยพระจุลจอมเกล้า', 'Chulachomklao Royal Military Academy', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-20500', 'โรงเรียนนายเรือ', 'Royal Thai Naval Academy', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-20600', 'โรงเรียนนายเรืออากาศนวมินทกษัตริยาธิราช', 'Navaminda Kasatriyadhiraj Royal Thai Air Force Academy', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-20700', 'วิทยาลัยแพทยศาสตร์พระมงกุฎเกล้า', 'Phramongkutklao College of Medicine', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-20800', 'วิทยาลัยพยาบาลกองทัพบก', 'Royal Thai Army Nursing College', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-20900', 'วิทยาลัยพยาบาลกองทัพเรือ', 'Royal Thai Navy College of Nursing', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-21000', 'วิทยาลัยพยาบาลทหารอากาศ', 'Royal Thai Air Force Nursing College', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-21100', 'โรงเรียนนายร้อยตำรวจ', 'Royal Police Cadet Academy', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-21200', 'วิทยาลัยพยาบาลตำรวจ', 'Police Nursing College', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-21300', 'ศูนย์ฝึกพาณิชย์นาวี', 'Merchant Marine Training Centre', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-21400', 'สถาบันพระบรมราชชนก', 'Praboromarajchanok Institute', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-21401', 'วิทยาลัยพยาบาลบรมราชชนนี กรุงเทพ', 'Boromarajonani College of Nursing, Bangkok', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-21402', 'วิทยาลัยพยาบาลบรมราชชนนี ขอนแก่น', 'Boromarajonani College of Nursing, Khon Kaen', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-21403', 'วิทยาลัยพยาบาลบรมราชชนนี จักรีรัช', 'Boromarajonani College of Nursing, Ratchaburi', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-21404', 'วิทยาลัยพยาบาลบรมราชชนนี ชลบุรี', 'Boromarajonani College of Nursing, Chon Buri', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-21405', 'วิทยาลัยพยาบาลบรมราชชนนี ชัยนาท', 'Boromarajonani College of Nursing, Chai Nat', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-21406', 'วิทยาลัยพยาบาลบรมราชชนนี เชียงใหม่', 'Boromarajonani College of Nursing, Chiang Mai', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-21407', 'วิทยาลัยพยาบาลบรมราชชนนี ตรัง', 'Boromarajonani College of Nursing, Trang', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-21408', 'วิทยาลัยพยาบาลบรมราชชนนี นนทบุรี', 'Boromarajonani College of Nursing, Nonthaburi', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-21409', 'วิทยาลัยพยาบาลบรมราชชนนี นพรัตน์วชิระ', 'Boromarajonani College of Nursing, Bangkok', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-21410', 'วิทยาลัยพยาบาลบรมราชชนนี นครลำปาง', 'Boromarajonani College of Nursing, Lampang', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-21411', 'วิทยาลัยพยาบาลบรมราชชนนี นครราชสีมา', 'Boromarajonani College of Nursing, Nakhon Ratchasima', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-21413', 'วิทยาลัยพยาบาลบรมราชชนนี นครศรีธรรมราช', 'Boromarajonani College of Nursing, Nakhon Si Thammarat', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-21414', 'วิทยาลัยพยาบาลบรมราชชนนี นราธิวาส', 'Boromarajonani College of Nursing, Narathiwat', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-21415', 'วิทยาลัยพยาบาลบรมราชชนนี พระพุทธบาท', 'Boromarajonani College of Nursing, Saraburi', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-21416', 'วิทยาลัยพยาบาลพระจอมเกล้า เพชรบุรี', 'Phrachomklao College of Nursing, Phetchaburi', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-21417', 'วิทยาลัยพยาบาลพระปกเกล้า จันทบุรี', 'Phrapokklao Nursing College, Chanthaburi', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-21418', 'วิทยาลัยพยาบาลบรมราชชนนี พุทธชินราช', 'Boromarajonani College of Nursing, Phitsanulok', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-21419', 'วิทยาลัยพยาบาลบรมราชชนนี พะเยา', 'Boromarajonani College of Nursing, Phayao', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-21420', 'วิทยาลัยพยาบาลบรมราชชนนี ยะลา', 'Boromarajonani College of Nursing, Yala', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-21421', 'วิทยาลัยพยาบาลบรมราชชนนี ราชบุรี', 'Boromarajonani College of Nursing, Ratchaburi', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-21422', 'วิทยาลัยพยาบาลศรีมหาสารคาม', 'Srimahasarakham Nursing College', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-21423', 'วิทยาลัยพยาบาลบรมราชชนนี สระบุรี', 'Boromarajonani College of Nursing, Saraburi', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-21424', 'วิทยาลัยพยาบาลบรมราชชนนี สุพรรณบุรี', 'Boromarajonani College of Nursing, Suphan Buri', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-21425', 'วิทยาลัยพยาบาลบรมราชชนนี สวรรค์ประชารักษ์', 'Boromarajonani College of Nursing, Nakhon Sawan', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-21426', 'วิทยาลัยพยาบาลบรมราชชนนี สุรินทร์', 'Boromarajonani College of Nursing, Surin', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-21427', 'วิทยาลัยพยาบาลบรมราชชนนี สรรพสิทธิประสงค์ อุบลราชธานี', 'Boromarajonani College of Nursing, Ubon Ratchathani', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-21428', 'วิทยาลัยพยาบาลบรมราชชนนี สุราษฎร์ธานี', 'Boromarajonani College of Nursing, Surat Thani', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-21429', 'วิทยาลัยพยาบาลบรมราชชนนี สงขลา', 'Boromarajonani College of Nursing, Songkhla', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-21430', 'วิทยาลัยพยาบาลบรมราชชนนี อุตรดิตถ์', 'Boromarajonani College of Nursing, Uttaradit', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-21431', 'วิทยาลัยพยาบาลบรมราชชนนี อุดรธานี', 'Boromarajonani College of Nursing, Udon Thani', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-21432', 'วิทยาลัยการสาธารณสุขสิรินธร ขอนแก่น', 'Sirindhorn College of Public Health, Khon Kaen', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-21433', 'วิทยาลัยการสาธารณสุขสิรินธร ชลบุรี', 'Sirindhorn College of Public Health, Chon Buri', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-21434', 'วิทยาลัยการสาธารณสุขสิรินธร ตรัง', 'Sirindhorn College of Public Health, Trang', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-21435', 'วิทยาลัยการสาธารณสุขสิรินธร พิษณุโลก', 'Sirindhorn College of Public Health, Phitsanulok', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-21436', 'วิทยาลัยการสาธารณสุขสิรินธร ยะลา', 'Sirindhorn College of Public Health, Yala', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-21437', 'วิทยาลัยการสาธารณสุขสิรินธร สุพรรณบุรี', 'Sirindhorn College of Public Health, Suphan Buri', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-21438', 'วิทยาลัยพยาบาลสรรพสิทธิประสงค์ อุบลราชธานี', 'Sappasitthiprasong Nursing College, Ubon Ratchathani', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-21439', 'วิทยาลัยการสาธารณสุขสิรินธร อุบลราชธานี', 'Sirindhorn College of Public Health, Ubon Ratchathani', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-21440', 'วิทยาลัยเทคโนโลยีทางการแพทย์และสาธารณสุข กาญจนาภิเษก', 'Kanchanabhishek Institute of Medical and Public Health Technology', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-21441', 'วิทยาลัยพยาบาลบรมราชชนนี แพร่', 'Boromarajonani College of Nursing, Phrae', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-21442', 'วิทยาลัยการแพทย์แผนไทยอภัยภูเบศร', 'Abhaibhubejhr College of Thai Traditional Medicine', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-21700', 'วิทยาลัยการชลประทาน', 'Irrigation College', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-21800', 'สถาบันการพยาบาลศรีสวรินทิราสภากาชาดไทย', 'Srisavarindhira Thai Red Cross Institute of Nursing', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-21900', 'สถาบันบัณฑิตพัฒนศิลป์', 'Bunditpatanasilpa Institute', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-22000', 'มหาวิทยาลัยการกีฬาแห่งชาติ', 'Thailand National Sports University', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-22001', 'มหาวิทยาลัยการกีฬาแห่งชาติ วิทยาเขตกระบี่', 'Thailand National Sports University — Campus, Krabi (22001)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-22002', 'มหาวิทยาลัยการกีฬาแห่งชาติ วิทยาเขตกรุงเทพ', 'Thailand National Sports University — Campus, Bangkok (22002)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-22003', 'มหาวิทยาลัยการกีฬาแห่งชาติ วิทยาเขตชลบุรี', 'Thailand National Sports University — Campus, Chon Buri (22003)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-22004', 'มหาวิทยาลัยการกีฬาแห่งชาติ วิทยาเขตชัยภูมิ', 'Thailand National Sports University — Campus, Chaiyaphum (22004)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-22005', 'มหาวิทยาลัยการกีฬาแห่งชาติ วิทยาเขตชุมพร', 'Thailand National Sports University — Campus, Chumphon (22005)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-22006', 'มหาวิทยาลัยการกีฬาแห่งชาติ วิทยาเขตเชียงใหม่', 'Thailand National Sports University — Campus, Chiang Mai (22006)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-22007', 'มหาวิทยาลัยการกีฬาแห่งชาติ วิทยาเขตตรัง', 'Thailand National Sports University — Campus, Trang (22007)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-22008', 'มหาวิทยาลัยการกีฬาแห่งชาติ วิทยาเขตเพชรบูรณ์', 'Thailand National Sports University — Campus, Phetchabun (22008)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-22009', 'มหาวิทยาลัยการกีฬาแห่งชาติ วิทยาเขตมหาสารคาม', 'Thailand National Sports University — Campus, Maha Sarakham (22009)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-22010', 'มหาวิทยาลัยการกีฬาแห่งชาติ วิทยาเขตยะลา', 'Thailand National Sports University — Campus, Yala (22010)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-22011', 'มหาวิทยาลัยการกีฬาแห่งชาติ วิทยาเขตลำปาง', 'Thailand National Sports University — Campus, Lampang (22011)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-22012', 'มหาวิทยาลัยการกีฬาแห่งชาติ วิทยาเขตศรีสะเกษ', 'Thailand National Sports University — Campus, Sisaket (22012)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-22013', 'มหาวิทยาลัยการกีฬาแห่งชาติ วิทยาเขตสมุทรสาคร', 'Thailand National Sports University — Campus, Samut Sakhon (22013)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-22014', 'มหาวิทยาลัยการกีฬาแห่งชาติ วิทยาเขตสุโขทัย', 'Thailand National Sports University — Campus, Sukhothai (22014)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-22015', 'มหาวิทยาลัยการกีฬาแห่งชาติ วิทยาเขตสุพรรณบุรี', 'Thailand National Sports University — Campus, Suphan Buri (22015)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-22016', 'มหาวิทยาลัยการกีฬาแห่งชาติ วิทยาเขตอ่างทอง', 'Thailand National Sports University — Campus, Ang Thong (22016)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-22017', 'มหาวิทยาลัยการกีฬาแห่งชาติ วิทยาเขตอุดรธานี', 'Thailand National Sports University — Campus, Udon Thani (22017)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-22100', 'สถาบันการบินพลเรือน', 'Civil Aviation Training Center', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-22400', 'มหาวิทยาลัยกรุงเทพสุวรรณภูมิ', 'Bangkok Suvarnabhumi University', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-22500', 'วิทยาลัยเทคโนโลยีสยาม', 'Siam Technology College', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-22501', 'วิทยาลัยเทคโนโลยีสยาม วิทยาเขตราชบุรี', 'Siam Technology College — Campus, Ratchaburi (22501)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-22600', 'มหาวิทยาลัยราชพฤกษ์', 'Rajapruk University', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-22700', 'ราชวิทยาลัยจุฬาภรณ์', 'Chulabhorn Royal Academy', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-22800', 'สถาบันเทคโนโลยีไทย-ญี่ปุ่น', 'Thai-Nichi Institute of Technology', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-22900', 'สถาบันอาศรมศิลป์', 'Arsom Silp Institute of the Arts', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-23000', 'สถาบันวิทยาการประกอบการแห่งอโยธยา', 'Institute of Entrepreneurial Science Ayothaya', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-23400', 'สถาบันบัณฑิตศึกษาจุฬาภรณ์', 'Chulabhorn Graduate Institute', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-25000', 'สถาบันการจัดการปัญญาภิวัฒน์', 'Panyapiwat Institute of Management', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-25001', 'สถาบันการจัดการปัญญาภิวัฒน์ วิทยาเขตอีอีซี', 'Panyapiwat Institute of Management — Campus, Chon Buri (25001)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-26000', 'วิทยาลัยเทคโนโลยีพนมวันท์', 'Phanomwan College of Technology', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-26100', 'วิทยาลัยพิชญบัณฑิต', 'Pitchayabundit College', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-26200', 'สถาบันกันตนา', 'Kantana Institute', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-26300', 'สถาบันการเรียนรู้เพื่อปวงชน', 'Learning Institute For Everyone', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-26400', 'สถาบันเทคโนโลยียานยนต์มหาชัย', 'Mahachai Institute of Automotive Technology', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-26500', 'สถาบันดนตรีกัลยาณิวัฒนา', 'Princess Galyani Vadhana Institute of Music', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-26600', 'มหาวิทยาลัยนวมินทราธิราช', 'Navamindradhiraj University', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-26700', 'สถาบันเทคโนโลยีจิตรลดา', 'Chitralada Technology Institute', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-26800', 'สถาบันวิทยาการจัดการแห่งแปซิฟิค', 'Pacific Institute of Management Science', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-26801', 'สถาบันวิทยาการจัดการแห่งแปซิฟิค วิทยาเขตนิมิตใหม่', 'Pacific Institute of Management Science — Campus, Pathum Thani (26801)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-28800', 'สถาบันเทคโนโลยีแห่งสุวรรณภูมิ', 'Suvarnabhumi Institute of Technology', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-28900', 'สถาบันวิทยสิริเมธี', 'Vidyasirimedhi Institute of Science and Technology', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-29400', 'โรงเรียนเสนาธิการทหารบก', 'Command and General Staff College', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mhesi-29500', 'วิทยาลัยนานาชาติราฟเฟิลส์', 'Raffles International College', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT ("nameTh") DO UPDATE SET
  "nameEn" = EXCLUDED."nameEn",
  "isActive" = true,
  "updatedAt" = CURRENT_TIMESTAMP;
